/**
 * Interactive `.env` wizard, called by `make setup` and `install.sh`. A fresh
 * checkout gets a complete `.env`; an existing one gets a password change that
 * rewrites *only* `API_KEY_HASH`, since people keep `CLAUDE_API_KEY` and
 * `DATABASE_URL` in there.
 *
 *     bun run setup            # interactive setup / password change
 *     bun run setup --force    # skip the confirmation prompt
 *     bun run setup --check    # exit 0 if .env is configured, 1 if not
 *
 * The standalone executable calls {@link ensureEnvConfigured} instead — same
 * wizard, reached on first launch rather than from a Makefile the user of a
 * downloaded binary never sees.
 */

import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline'
import { join } from 'node:path'
import { Writable } from 'node:stream'

import { resolveProjectRoot } from '@/config/paths'

/** Cost factor; 12 matches the hashes existing `.env` files already carry. */
const BCRYPT_COST = 12

// `.env.example` ships a syntactically valid `API_KEY_HASH=…example…`, so
// checking for the key alone would call a copied example file "configured".
const HASH_PLACEHOLDERS = ['example_hash', 'paste_your', 'paste_here']
const JWT_PLACEHOLDERS = ['your-random-secret', 'key-here']

export function isConfigured(envFile: string): boolean {
  if (!existsSync(envFile)) return false
  const content = readFileSync(envFile, 'utf-8')

  const hasHash =
    content.includes('API_KEY_HASH=') && !HASH_PLACEHOLDERS.some((p) => content.includes(p))
  const hasJwt =
    content.includes('JWT_SECRET=') && !JWT_PLACEHOLDERS.some((p) => content.includes(p))

  return hasHash && hasJwt
}

// Muting intercepts readline's own output stream rather than using raw mode,
// which would also cost line editing, backspace and Ctrl-C.
function ask(question: string, hidden = false): Promise<string> {
  return new Promise((resolve, reject) => {
    let muted = false
    const mutedOutput = new Writable({
      write(chunk, _encoding, callback) {
        if (!muted) process.stdout.write(chunk as Buffer)
        callback()
      },
    })

    const rl = createInterface({
      input: process.stdin,
      output: hidden ? mutedOutput : process.stdout,
      terminal: true,
    })

    rl.question(question, (answer) => {
      if (hidden) process.stdout.write('\n')
      rl.close()
      resolve(answer)
    })
    rl.on('SIGINT', () => {
      rl.close()
      reject(new Error('cancelled'))
    })

    if (hidden) {
      process.stdout.write(question)
      muted = true
    }
  })
}

async function promptPasswordHash(): Promise<string> {
  for (;;) {
    const password = await ask('Enter password: ', true)
    if (password.length < 4) {
      console.log('Password must be at least 4 characters. Please try again.')
      continue
    }

    const confirm = await ask('Confirm password: ', true)
    if (password !== confirm) {
      console.log('Passwords do not match. Please try again.')
      continue
    }

    if (password.length < 8) {
      console.log('\nNote: Password is less than 8 characters.')
      const proceed = (await ask('Continue? (Y/n): ')).trim().toLowerCase()
      if (proceed === 'n') continue
    }

    return await Bun.password.hash(password, { algorithm: 'bcrypt', cost: BCRYPT_COST })
  }
}

function envFileContent(passwordHash: string, jwtSecret: string, userName: string): string {
  return `USER_NAME=${userName}
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Database Configuration
# Default: SQLite (file: ./claudeworld.db, no installation needed)
DATABASE_URL=sqlite+aiosqlite:///./claudeworld.db

# Claude API Configuration
# Option 1: Use direct API key authentication (recommended for deployment)
# Get your API key from: https://console.anthropic.com/settings/keys
# CLAUDE_API_KEY=sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#
# Option 2: Use Claude Code web authentication (when running through Claude Code with subscription)
# If CLAUDE_API_KEY is not set, the backend will use Claude Code authentication

# Authentication (auto-generated by setup wizard)
API_KEY_HASH=${passwordHash}

# JWT Secret (auto-generated)
JWT_SECRET=${jwtSecret}

# Enable Guest Login (Optional)
ENABLE_GUEST_LOGIN=true

# Agent Debugging
# Set to "true" to enable detailed debug logging for agent interactions
DEBUG_AGENTS=false
`
}

// Replaces an uncommented `KEY=…` line, or appends one.
function setEnvVar(content: string, key: string, value: string): string {
  const pattern = new RegExp(`^${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}=.*$`, 'm')
  if (pattern.test(content)) return content.replace(pattern, `${key}=${value}`)

  const separator = content === '' || content.endsWith('\n') ? '' : '\n'
  return `${content}${separator}${key}=${value}\n`
}

export async function runSetupWizard(envFile: string): Promise<void> {
  console.log('='.repeat(60))
  console.log('ClaudeWorld - Initial Setup')
  console.log('='.repeat(60))
  console.log('\nWelcome! Let’s set up your application.\n')

  const passwordHash = await promptPasswordHash()
  const jwtSecret = randomBytes(32).toString('hex')
  const userName = (await ask('\nEnter display name (default: User): ')).trim() || 'User'

  writeFileSync(envFile, envFileContent(passwordHash, jwtSecret, userName), 'utf-8')
  console.log(`\nConfiguration saved: ${envFile}`)
}

async function updateExistingEnv(envFile: string): Promise<void> {
  console.log('='.repeat(60))
  console.log('ClaudeWorld - Change Password')
  console.log('='.repeat(60))
  console.log(`\nUpdating the login password in ${envFile}`)
  console.log('(all other settings are left untouched)\n')

  const passwordHash = await promptPasswordHash()

  let content = readFileSync(envFile, 'utf-8')
  content = setEnvVar(content, 'API_KEY_HASH', passwordHash)

  // A .env without a usable JWT secret cannot issue tokens -- fill one in.
  const hasUsableJwt = /^JWT_SECRET=(?!your-random-secret|.*key-here$).+$/m.test(content)
  if (!hasUsableJwt) {
    content = setEnvVar(content, 'JWT_SECRET', randomBytes(32).toString('hex'))
    console.log('Generated a missing JWT_SECRET.')
  }

  writeFileSync(envFile, content, 'utf-8')
  console.log(`\nPassword updated: ${envFile}`)
}

/**
 * Bring `<root>/.env` into a usable state before the server reads it, running
 * the wizard when it is not.
 *
 * Returns false when there is no way to ask — a service manager, a double-click
 * on a platform that gave the process no console — in which case the caller
 * should print instructions and exit rather than start a server that will 401
 * every login. The TTY check is on *stdin* specifically: that is what readline
 * needs, and a binary launched from Explorer gets a console with a usable one.
 */
export async function ensureEnvConfigured(projectRoot: string): Promise<boolean> {
  const envFile = join(projectRoot, '.env')
  if (isConfigured(envFile)) return true

  if (!process.stdin.isTTY) return false

  await runSetupWizard(envFile)
  return true
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const force = args.includes('--force')
  const checkOnly = args.includes('--check')

  const envFile = join(resolveProjectRoot(), '.env')

  if (checkOnly) {
    if (isConfigured(envFile)) {
      console.log('✅ .env is configured')
      process.exit(0)
    }
    console.log('❌ .env is not configured')
    process.exit(1)
  }

  if (isConfigured(envFile)) {
    if (!force) {
      console.log('✅ .env is already configured!')
      console.log(`   Location: ${envFile}\n`)
      const answer = (await ask('Change the login password? (y/N): ')).trim().toLowerCase()
      if (answer !== 'y' && answer !== 'yes') {
        console.log('Nothing changed.')
        return
      }
      console.log()
    }
    await updateExistingEnv(envFile)
  } else {
    await runSetupWizard(envFile)
  }

  console.log()
  console.log('='.repeat(60))
  console.log('✅ Setup complete!')
  console.log('='.repeat(60))
  console.log('\nYou can now run the application with:\n   make dev\n')
}

// Guarded: the executable imports this module for `ensureEnvConfigured`, and an
// unguarded call would run the whole argv-parsing wizard on import.
if (import.meta.main) {
  main().catch((error: unknown) => {
    if (error instanceof Error && error.message === 'cancelled') {
      console.log('\n\nSetup cancelled.')
      process.exit(1)
    }
    console.error(error)
    process.exit(1)
  })
}
