"""
Launcher script for the packaged ClaudeWorld application.

This is the entry point for the PyInstaller bundle. It:
1. Sets up paths for bundled resources
2. Runs first-time setup wizard if needed
3. Starts the uvicorn server
4. Opens the browser to the application
"""

import getpass
import os
import secrets
import sys
import webbrowser
from pathlib import Path
from threading import Timer


def get_base_path() -> Path:
    """Get the base path for resources (handles both dev and bundled modes)."""
    if getattr(sys, "frozen", False):
        # Running as PyInstaller bundle
        return Path(sys._MEIPASS)
    else:
        # Running in development
        return Path(__file__).parent.parent


def get_work_dir() -> Path:
    """Get the working directory for user data (.env, agents, etc.)."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    else:
        return Path(__file__).parent.parent


def setup_paths():
    """Set up Python paths for imports."""
    base_path = get_base_path()

    # Add backend to Python path
    backend_path = base_path / "backend"
    if backend_path.exists():
        sys.path.insert(0, str(backend_path))
    else:
        # In dev mode, backend is current directory's parent
        sys.path.insert(0, str(Path(__file__).parent))

    # Set working directory
    work_dir = get_work_dir()
    os.chdir(work_dir)


def copy_default_agents():
    """Copy default agents if they don't exist."""
    if not getattr(sys, "frozen", False):
        return

    base_path = get_base_path()
    work_dir = get_work_dir()

    agents_dest = work_dir / "agents"
    agents_src = base_path / "agents"
    if not agents_dest.exists() and agents_src.exists():
        import shutil

        shutil.copytree(agents_src, agents_dest)
        print(f"Default agents copied: {agents_dest}")


def is_env_configured(env_file: Path) -> bool:
    """Check if .env file has valid configuration."""
    if not env_file.exists():
        return False

    content = env_file.read_text(encoding="utf-8")

    # Check for placeholder values that indicate unconfigured state
    has_valid_hash = "API_KEY_HASH=" in content and "example_hash" not in content and "paste_your" not in content
    has_valid_jwt = "JWT_SECRET=" in content and "your-random-secret" not in content

    return has_valid_hash and has_valid_jwt


def run_first_time_setup():
    """Run interactive first-time setup wizard."""
    import bcrypt

    print("=" * 60)
    print("ClaudeWorld - Initial Setup")
    print("=" * 60)
    print()
    print("Welcome! Let's set up your application.")
    print()

    # Get password from user
    while True:
        password = getpass.getpass("Enter password: ")
        if len(password) < 4:
            print("Password must be at least 4 characters. Please try again.")
            continue

        password_confirm = getpass.getpass("Confirm password: ")
        if password != password_confirm:
            print("Passwords do not match. Please try again.")
            continue

        if len(password) < 8:
            print("\nNote: Password is less than 8 characters.")
            proceed = input("Continue? (Y/n): ").strip().lower()
            if proceed == "n":
                continue

        break

    # Generate password hash
    salt = bcrypt.gensalt()
    password_hash = bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")

    # Generate JWT secret
    jwt_secret = secrets.token_hex(32)

    # Get user name (optional)
    user_name = input("\nEnter display name (default: User): ").strip()
    if not user_name:
        user_name = "User"

    return {
        "password_hash": password_hash,
        "jwt_secret": jwt_secret,
        "user_name": user_name,
    }


def create_env_file(env_file: Path, config: dict):
    """Create .env file with user configuration."""
    env_content = f"""USER_NAME={config["user_name"]}
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Database URL (SQLite by default)
DATABASE_URL=sqlite+aiosqlite:///./claudeworld.db

# Authentication (auto-generated by setup wizard)
API_KEY_HASH={config["password_hash"]}

# JWT Secret (auto-generated)
JWT_SECRET={config["jwt_secret"]}

# Memory System Mode: RECALL (on-demand) or BRAIN (automatic)
MEMORY_BY=RECALL

# Set to "true" for debug logging
DEBUG_AGENTS=false

# Enable guest login (default: true)
ENABLE_GUEST_LOGIN=true
"""

    env_file.write_text(env_content, encoding="utf-8")
    print(f"\nConfiguration saved: {env_file}")


def setup_environment() -> bool:
    """Set up environment for the bundled application. Returns True if setup was run."""
    work_dir = get_work_dir()
    env_file = work_dir / ".env"

    # Copy default agents
    copy_default_agents()

    # Check if setup is needed
    if is_env_configured(env_file):
        return False

    # Run first-time setup
    try:
        config = run_first_time_setup()
        create_env_file(env_file, config)
        print()
        print("=" * 60)
        print("Setup complete! Starting application...")
        print("=" * 60)
        print()
        return True
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)


def open_browser():
    """Open the browser to the application."""
    webbrowser.open("http://localhost:8000")


def main():
    """Main entry point."""
    # Set up paths first
    setup_paths()

    # Run environment setup (including first-time wizard if needed)
    setup_was_run = setup_environment()

    # Load .env file into os.environ BEFORE importing any modules that use os.getenv()
    # This is critical because database.py uses os.getenv("DATABASE_URL") at module level
    from dotenv import load_dotenv

    work_dir = get_work_dir()
    env_file = work_dir / ".env"
    if env_file.exists():
        load_dotenv(env_file, override=True)
        print(f"Environment loaded from: {env_file}")

    # Import uvicorn and app after setting up paths and loading environment
    import uvicorn

    print("=" * 60)
    print("ClaudeWorld")
    print("=" * 60)
    print()
    print("Server starting: http://localhost:8000")
    print("Press Ctrl+C to stop the server")
    print()

    # Open browser after a short delay
    Timer(2.0, open_browser).start()

    # Import the app directly instead of using string path
    # This works better with PyInstaller bundling
    from main import app

    # Run the server with the app object directly
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info",
    )


if __name__ == "__main__":
    main()
