#!/usr/bin/env python3
"""
Interactive .env setup wizard for ClaudeWorld.

On a fresh checkout it creates a properly configured .env file by:
1. Prompting for a password and generating a bcrypt hash
2. Generating a secure JWT secret
3. Asking for an optional display name
4. Creating the .env file with all required values

When .env already exists it offers to change the login password, rewriting only
API_KEY_HASH and leaving every other setting alone.

Usage:
    python backend/scripts/setup_env.py           # Interactive setup / password change
    python backend/scripts/setup_env.py --force   # Skip the confirmation prompt
    python backend/scripts/setup_env.py --check   # Just check if .env is configured
"""

import argparse
import getpass
import re
import secrets
import sys
from pathlib import Path

import bcrypt


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent.parent


def is_env_configured(env_file: Path) -> bool:
    """Check if .env file has valid configuration."""
    if not env_file.exists():
        return False

    content = env_file.read_text(encoding="utf-8")

    # Check for placeholder values that indicate unconfigured state
    has_valid_hash = (
        "API_KEY_HASH=" in content
        and "example_hash" not in content
        and "paste_your" not in content
        and "paste_here" not in content
    )
    has_valid_jwt = "JWT_SECRET=" in content and "your-random-secret" not in content and "key-here" not in content

    return has_valid_hash and has_valid_jwt


def prompt_password_hash() -> str:
    """Prompt for a password (with confirmation) and return its bcrypt hash."""
    while True:
        password = getpass.getpass("Enter password: ")
        if len(password) < 4:
            print("Password must be at least 4 characters. Please try again.")
            continue

        password_confirm = getpass.getpass("Confirm password: ")
        if password != password_confirm:
            print("Passwords do not match. Please try again.")
            continue

        if len(password) < 8:
            print("\nNote: Password is less than 8 characters.")
            proceed = input("Continue? (Y/n): ").strip().lower()
            if proceed == "n":
                continue

        break

    salt = bcrypt.gensalt()
    return bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")


def run_setup_wizard() -> dict:
    """Run interactive setup wizard. Returns config dict."""
    print("=" * 60)
    print("ClaudeWorld - Initial Setup")
    print("=" * 60)
    print()
    print("Welcome! Let's set up your application.")
    print()

    # Get password from user
    password_hash = prompt_password_hash()

    # Generate JWT secret
    jwt_secret = secrets.token_hex(32)

    # Get user name (optional)
    user_name = input("\nEnter display name (default: User): ").strip()
    if not user_name:
        user_name = "User"

    return {
        "password_hash": password_hash,
        "jwt_secret": jwt_secret,
        "user_name": user_name,
    }


def create_env_file(env_file: Path, config: dict):
    """Create .env file with user configuration."""
    env_content = f"""USER_NAME={config["user_name"]}
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Database Configuration
# Default: SQLite (file: ./claudeworld.db, no installation needed)
# For PostgreSQL: Uncomment and configure the line below
# DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/claudeworld

# Claude API Configuration
# Option 1: Use direct API key authentication (recommended for deployment)
# Get your API key from: https://console.anthropic.com/settings/keys
# CLAUDE_API_KEY=sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#
# Option 2: Use Claude Code web authentication (when running through Claude Code with subscription)
# If CLAUDE_API_KEY is not set, the backend will use Claude Code authentication

# Authentication (auto-generated by setup wizard)
API_KEY_HASH={config["password_hash"]}

# JWT Secret (auto-generated)
JWT_SECRET={config["jwt_secret"]}

# Enable Guest Login (Optional)
ENABLE_GUEST_LOGIN=true

# Agent Debugging
# Set to "true" to enable detailed debug logging for agent interactions
DEBUG_AGENTS=false
"""

    env_file.write_text(env_content, encoding="utf-8")
    print(f"\nConfiguration saved: {env_file}")


def _set_env_var(content: str, key: str, value: str) -> str:
    """Replace an uncommented `KEY=...` line, or append it if absent."""
    pattern = re.compile(rf"^{re.escape(key)}=.*$", re.MULTILINE)
    if pattern.search(content):
        return pattern.sub(lambda _: f"{key}={value}", content, count=1)

    separator = "" if content.endswith("\n") or not content else "\n"
    return f"{content}{separator}{key}={value}\n"


def update_existing_env(env_file: Path):
    """Prompt for a new password and update API_KEY_HASH in place.

    All other settings in the existing .env (API keys, database URL, ...) are
    preserved -- only the password hash is rewritten.
    """
    print("=" * 60)
    print("ClaudeWorld - Change Password")
    print("=" * 60)
    print()
    print(f"Updating the login password in {env_file}")
    print("(all other settings are left untouched)")
    print()

    password_hash = prompt_password_hash()

    content = env_file.read_text(encoding="utf-8")
    content = _set_env_var(content, "API_KEY_HASH", password_hash)

    # A .env without a usable JWT secret cannot issue tokens -- fill one in.
    if not re.search(r"^JWT_SECRET=(?!your-random-secret|.*key-here$).+$", content, re.MULTILINE):
        content = _set_env_var(content, "JWT_SECRET", secrets.token_hex(32))
        print("Generated a missing JWT_SECRET.")

    env_file.write_text(content, encoding="utf-8")
    print(f"\nPassword updated: {env_file}")


def main():
    parser = argparse.ArgumentParser(description="ClaudeWorld .env setup wizard")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Skip the confirmation prompt when .env is already configured",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Just check if .env is configured (exit 0 if yes, 1 if no)",
    )
    args = parser.parse_args()

    project_root = get_project_root()
    env_file = project_root / ".env"

    # Check-only mode
    if args.check:
        if is_env_configured(env_file):
            print("✅ .env is configured")
            sys.exit(0)
        else:
            print("❌ .env is not configured")
            sys.exit(1)

    try:
        if is_env_configured(env_file):
            # Already set up: offer to change the password, keeping everything else.
            if not args.force:
                print("✅ .env is already configured!")
                print(f"   Location: {env_file}")
                print()
                answer = input("Change the login password? (y/N): ").strip().lower()
                if answer not in ("y", "yes"):
                    print("Nothing changed.")
                    return
                print()
            update_existing_env(env_file)
        else:
            config = run_setup_wizard()
            create_env_file(env_file, config)

        print()
        print("=" * 60)
        print("✅ Setup complete!")
        print("=" * 60)
        print()
        print("You can now run the application with:")
        print("   make dev")
        print()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)


if __name__ == "__main__":
    main()
