"""baseline schema

The whole schema as models.py defined it when Alembic was adopted.

Fresh installs run this. Databases that predate Alembic never do -- they are
brought up to date by the legacy catch-up in ``migrations.py``, verified against
models.py, and then stamped at this revision (see ``init_db``). That is why
there are no per-table revisions reproducing the old hand-written ALTERs: every
database that needs them is pre-Alembic by definition, and every database that
does not already matches this baseline.

Revision ID: e872d9c86c83
Revises:
Create Date: 2026-08-06 12:57:57.252748

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e872d9c86c83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('world_name', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('config_file', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('in_a_nutshell', sa.Text(), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('recent_events', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('interrupt_every_turn', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('transparent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_world_name'), ['world_name'], unique=False)
        batch_op.create_index('ux_agents_name_world', ['name', 'world_name'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_interactions', sa.Integer(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_world_id'), ['world_id'], unique=False)
        batch_op.create_index('ux_rooms_owner_name_world', ['owner_id', 'name', 'world_id'], unique=True)

    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('language', sa.Enum('en', 'ko', 'jp', name='language'), nullable=True),
    sa.Column('phase', sa.Enum('onboarding', 'active', 'ended', name='worldphase'), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('stat_definitions', sa.Text(), nullable=True),
    sa.Column('onboarding_room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worlds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worlds_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_worlds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ux_worlds_owner_name', ['owner_id', 'name'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('adjacent_locations', sa.Text(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_discovered', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_location_world', ['world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole'), nullable=False),
    sa.Column('participant_type', sa.String(), nullable=True),
    sa.Column('participant_name', sa.String(), nullable=True),
    sa.Column('thinking', sa.Text(), nullable=True),
    sa.Column('anthropic_calls', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('image_media_type', sa.String(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('game_time_snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_message_chat_session', ['room_id', 'chat_session_id'], unique=False)
        batch_op.create_index('idx_message_room_id', ['room_id'], unique=False)
        batch_op.create_index('idx_message_room_timestamp', ['room_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    op.create_table('room_agent_sessions',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'agent_id')
    )
    op.create_table('room_agents',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'agent_id')
    )
    op.create_table('player_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('inventory', sa.Text(), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('action_history', sa.Text(), nullable=True),
    sa.Column('is_chat_mode', sa.Boolean(), nullable=True),
    sa.Column('chat_mode_start_message_id', sa.Integer(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id')
    )
    with op.batch_alter_table('player_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_states_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_states_id'))

    op.drop_table('player_states')
    op.drop_table('room_agents')
    op.drop_table('room_agent_sessions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_session_id'))
        batch_op.drop_index('idx_message_room_timestamp')
        batch_op.drop_index('idx_message_room_id')
        batch_op.drop_index('idx_message_chat_session')
        batch_op.drop_index('idx_message_agent_id')

    op.drop_table('messages')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))
        batch_op.drop_index('ix_location_world')

    op.drop_table('locations')
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.drop_index('ux_worlds_owner_name')
        batch_op.drop_index(batch_op.f('ix_worlds_owner_id'))
        batch_op.drop_index(batch_op.f('ix_worlds_name'))
        batch_op.drop_index(batch_op.f('ix_worlds_id'))

    op.drop_table('worlds')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ux_rooms_owner_name_world')
        batch_op.drop_index(batch_op.f('ix_rooms_world_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_name'))
        batch_op.drop_index(batch_op.f('ix_rooms_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('ux_agents_name_world')
        batch_op.drop_index(batch_op.f('ix_agents_world_name'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index(batch_op.f('ix_agents_id'))
        batch_op.drop_index(batch_op.f('ix_agents_group'))

    op.drop_table('agents')
    # ### end Alembic commands ###
