/**
 * JWT issue and verify.
 *
 * Ported from the token half of `backend/infrastructure/auth.py` (PyJWT →
 * jose). HS256, the same five claims, the same secret: a token minted by either
 * backend verifies in the other, which is what lets the frontend keep a token
 * in `localStorage` across the cutover instead of forcing everyone to log in
 * again. `src/tests/jwt.test.ts` pins that with a token generated by PyJWT.
 */

import { jwtVerify, SignJWT } from 'jose'

import { getLogger } from '../infrastructure/logging/logger'
import { resolveAuthConfig } from './config'
import { isUserRole, type UserRole } from './roles'

const logger = getLogger('Auth')

/** Python's `generate_jwt_token` default: seven days. */
export const DEFAULT_EXPIRATION_HOURS = 168

/** The `type` claim every token carries; verified on the way back in. */
const TOKEN_TYPE = 'access_token'

export interface TokenPayload {
  exp: number
  iat: number
  type: string
  role: string
  user_id?: string
}

/**
 * Encode the signing secret, defaulting to the configured one.
 *
 * Throws rather than exiting the process — `assertAuthConfigured` is what turns
 * a missing secret into a refusal to start, and it runs once at boot.
 */
function encodeSecret(secret: string | null | undefined): Uint8Array {
  const resolved = secret ?? resolveAuthConfig().jwtSecret
  if (!resolved) throw new Error('JWT_SECRET is not set')
  return new TextEncoder().encode(resolved)
}

export interface GenerateTokenOptions {
  role?: UserRole
  expirationHours?: number
  /**
   * Stable identifier for the session. Guests get a random one so two guests
   * are distinguishable; admins are always `admin`.
   */
  userId?: string
  /** Signing secret; defaults to `JWT_SECRET`. */
  secret?: string
}

/** Twelve hex characters, matching Python's `secrets.token_hex(6)`. */
export function generateGuestUserId(): string {
  return `guest-${Buffer.from(crypto.getRandomValues(new Uint8Array(6))).toString('hex')}`
}

export async function generateJwtToken({
  role = 'admin',
  expirationHours = DEFAULT_EXPIRATION_HOURS,
  userId,
  secret,
}: GenerateTokenOptions = {}): Promise<string> {
  const resolvedUserId = userId ?? (role === 'guest' ? generateGuestUserId() : 'admin')

  // Seconds, floored — PyJWT converts the datetimes the same way, and a token
  // whose `iat` disagrees between backends by a fraction of a second would make
  // the expiry-window test flaky for no reason.
  const issuedAt = Math.floor(Date.now() / 1000)

  return new SignJWT({ type: TOKEN_TYPE, role, user_id: resolvedUserId })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt(issuedAt)
    .setExpirationTime(issuedAt + Math.round(expirationHours * 3600))
    .sign(encodeSecret(secret))
}

/**
 * Verify a token and return its claims, or null.
 *
 * Every failure mode collapses to null on purpose: the caller's only decision
 * is 401-or-not, and distinguishing "expired" from "forged" in the response
 * would tell an attacker which of the two they achieved.
 */
export async function validateJwtToken(
  token: string,
  secret?: string,
): Promise<TokenPayload | null> {
  try {
    const { payload } = await jwtVerify(token, encodeSecret(secret), { algorithms: ['HS256'] })
    return payload as unknown as TokenPayload
  } catch (error) {
    const code = (error as { code?: string }).code
    if (code === 'ERR_JWT_EXPIRED') {
      logger.warning('⚠️  JWT token has expired')
    } else {
      logger.warning(`⚠️  Invalid JWT token: ${String(error)}`)
    }
    return null
  }
}

/**
 * The role a token carries.
 *
 * Anything that is not exactly `"guest"` reads as admin, including a legacy
 * token minted before the claim existed. That is Python's behaviour and it is
 * load-bearing: tightening it would lock out every unexpired token issued
 * before roles were added.
 */
export function roleFromPayload(payload: TokenPayload | null): UserRole | null {
  if (!payload) return null
  const role = payload.role ?? 'admin'
  return role === 'guest' ? 'guest' : 'admin'
}

export async function getRoleFromToken(token: string, secret?: string): Promise<UserRole | null> {
  return roleFromPayload(await validateJwtToken(token, secret))
}

/**
 * The user id a token carries.
 *
 * Legacy tokens predate the claim, so they fall back to the role name — which
 * is why a legacy guest token yields the bare string `guest` rather than the
 * `guest-<hex>` form new ones get.
 */
export function userIdFromPayload(payload: TokenPayload | null): string | null {
  if (!payload) return null
  if (payload.user_id === undefined) return payload.role === 'guest' ? 'guest' : 'admin'
  return payload.user_id
}

export async function getUserIdFromToken(token: string, secret?: string): Promise<string | null> {
  return userIdFromPayload(await validateJwtToken(token, secret))
}

export { isUserRole }
